
CREATE DATABASE IF NOT EXISTS steam DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE steam;
CREATE TABLE IF NOT EXISTS games (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  genre VARCHAR(100),
  price DECIMAL(10,2) NOT NULL,
  time_to_finish DECIMAL(5,2) NOT NULL,
  total_playtime DECIMAL(5,2) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
